apiVersion: v1
kind: ConfigMap
metadata:
  name: ngix-configmap
data:
  custom.conf: |
    server { 
      listen: 80;
      location / { 
        return 200 'Hello from ConfigMap';
        
      }
   }
   

    
