apiVersion: v1
kind: PersistentVolume
metadata:
  name: nginx-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    server: 192.68.1.100
    path: /export/nginx-data
  PersistentVolumeReclaimPolicy: Retain
  
