apiVersion: v1
kind: secret
metadata: 
  name: nginx-secret
type: Opaque
data:
  username: yshwdj=  #base64 username
  password: hskshg=  #base64 password

#  or we can use imperative command to create secret
# kubectl create secret generic nginx-secret \
#   --literal-from=username=admin \
#   --literal-from=password=password \
#   --dry-run=client -o yaml > secret.yaml 
