// This yaml is for schedule a pod on specific node using nodeSelector
apiVersion: v1
kind: Pod
metadata: 
  labels:
    run: ngin
  name: ngin
spec:
  containers:
  - image: nginx
    name: nginx
    port:
      containerPort: 80 
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  nodeSelector:
     hdd: ssd


//kubectl apply -f pod.yaml     ...> Pod will be created but in pending state
// Kubectl get no --show-labels
// kubectl label nodes <node-name> hdd=ssd
// kubectl get po -o wide  ---> now pod will be up and can see the pod landed on node which is having label hdd=ssd
// kubectl label nodes <node-name> hdd-   --> Now label got removed and pod will be in pending state.
// kubectl get po 
