apiVersion: v1
kind: Pod
metadata:
   name: my-pod
spec:
  containers:
    - image: nginx:latest
      name: ngin
      ports:
      - containerPort: 80
      volumeMounts:
      - name: storage
        mountPath: /usr/share/nginx/html
  volumes:
  - name: storage
    persistentVolumeClaim: 
      claimName: my-pvc

      # This mounts a PersistentVolumeClaim (PVC) inside /usr/share/nginx/html.
    
