apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  labels:
    environment: Prod
    app: micro-1
spec:
  containers:
  - image: nginx:latest
    name: nginx-cont
    ports:
    - containerPort: 80 
  tolerations:
  - key: "hdd"
    operator: "Equal"
    value: "ssd"
    effect: "NoSchedule"

//$ kubectl taint no <node-name> hdd=ssd:NoSchedule
//$ kubectl get po
//$ kubectl apply -f pod.yaml
//$ kubectl get po -o wide ---> it will be landed on the node which we have added taint 
//$ kubectl taint no <node-name> hdd-
//$ kubectl get no
//$ kubectl describe nodes | grep Taints     ---> To check the taint 
//$ kubectl describe nodes <node-name> | grep Taints     --> to check for the specific node
